import { injectGlobal, keyframes } from 'styled-components'

import { color } from './style-utils'

/* tslint:disable no-unused-expression  */
injectGlobal`
* {
    box-sizing: border-box;
  }

  html {
    color: ${color.black};
    font-size: 12px;
    font-style: normal;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans",
      "Droid Sans", "Helvetica Neue", sans-serif;
    -webkit-font-smoothing: subpixel-antialiased;
    text-rendering: geometricPrecision;
  }

  body {
    margin: 0;
    padding: 0;
  }

  fieldset {
    border: none;
    margin: 0;
    padding: 0;
  }
`

export const rotate = keyframes`
  0% {
        transform: rotate(0deg);
    }

    to {
        transform: rotate(1turn);
    }
`

export const flip = keyframes`
/* ----------------------------------------------
 * Generated by Animista on 2017-3-17 15:2:20
 * http://animista.net
 * T: @cssanimista
 * ---------------------------------------------- */

  0%, 40% {
    transform: rotateX(0);
  }
  60%, 100% {
    transform: rotateX(-180deg);
  }
`
